USE Shopping
GO

DROP TABLE IF EXISTS Items
GO
DROP TABLE IF EXISTS ItemType
GO
DROP PROC IF EXISTS GetItems
GO
DROP PROC IF EXISTS CreateShoppinhList
GO
DROP TABLE IF EXISTS ShoppingList
GO